### ISSUE TITLE
install missing dependency freedesktop.platfrom 22.08

### ISSUE THREAD

**Issue by Razack-git** [adamthiede/signal-desktop-builder#1]
Install failed on not found required freedesktop.Platform/aarch64/22.08

`
# flatpak install signal-arm org.signal.Signal
Looking for matches…
Error: The application org.signal.Signal/aarch64/master requires the runtime org.freedesktop.Platform/aarch64/22.08 which was not found
`

**Comment by adamthiede** [comment]
Make sure you enable flathub, too.

If you're installing system-wide,
`sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

If you're installing just for your user,
`flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

**Comment by Razack-git** [comment]
i had used the remote-add command, maybe didn't run successful on a unstable connection.
now its work, thx for the help.

How can I fix the scalling?

**Comment by adamthiede** [comment]
Not sure what you mean by scaling - you'll have to be more descriptive, provide screenshots, etc. I don't run this myself.
